version: "2"
checks:
  file-lines:
    enabled: false
  method-lines:
    enabled: false
  similar-code:
    enabled: false
plugins:
  csslint:
    enabled: true
  eslint:
    enabled: true
    channel: eslint-5
  fixme:
    enabled: true
  nodesecurity:
    enabled: true
exclude_patterns:
- "thirdparty/"
- "test/example/"
